language: csharp
solution: TestEnvironmentSetup.sln
mono: none
dotnet: 2.1.500

addons:
  sonarcloud:
    organization: jbarnes-niu-github

script:
  - dotnet restore
  - sonar-scanner -X
  - dotnet test